### ISSUE TITLE
win11运行软件没反应

### ISSUE THREAD

**Issue by jizhong-xu** [tiny-craft/tiny-rdm#10]
我下载的是便携解压版本，我电脑的版本是Win11的22H2，操作系统版本是22621.2283，点击运行或管理员运行都没有反应，不显示任何界面

**Comment by 2vl** [comment]
安装 WebView2 试试
https://developer.microsoft.com/en-us/microsoft-edge/webview2/

**Comment by yogaxu** [comment]
> 安装 WebView2 试试 https://developer.microsoft.com/en-us/microsoft-edge/webview2/

win10，22H2，19045.3448，已安装webview2，同样无反应

**Comment by tiny-craft** [comment]
Duplicate of #6

**Comment by tiny-craft** [comment]
@yogaxu @jizhong-xu 试下这个debug版本看看打开有没有控制台显示一些有用的信息
[Tiny RDM-debug.zip](https://github.com/tiny-craft/tiny-rdm/files/12844356/Tiny.RDM-debug.zip)

**Comment by yogaxu** [comment]
> @yogaxu @jizhong-xu 试下这个debug版本看看打开有没有控制台显示一些有用的信息 [Tiny RDM-debug.zip](https://github.com/tiny-craft/tiny-rdm/files/12844356/Tiny.RDM-debug.zip)

Exception 0xc0000005 0x0 0xffffffffffffffff 0x7ff9e2a67aae
PC=0x7ff9e2a67aae

runtime.cgocall(0x9d5540, 0x1aa56c8)
        /usr/local/opt/go/libexec/src/runtime/cgocall.go:157 +0x3e fp=0xc0000bf9c8 sp=0xc0000bf990 pc=0x9699fe
syscall.SyscallN(0x7ffa659ee040, {0xc0002f43a8?, 0x1, 0x100?})
        /usr/local/opt/go/libexec/src/runtime/syscall_windows.go:544 +0x11d fp=0xc0000bfa50 sp=0xc0000bf9c8 pc=0x9d0b3d
syscall.(*Proc).Call(0xc00028d9c0, {0xc0002f43a8, 0x1, 0x1})
        /usr/local/opt/go/libexec/src/syscall/dll_windows.go:166 +0x7e fp=0xc0000bfae0 sp=0xc0000bfa50 pc=0x9eeb5e
syscall.(*LazyProc).Call(0xc0000d00c0, {0xc0002f43a8, 0x1, 0x1})
        /usr/local/opt/go/libexec/src/syscall/dll_windows.go:286 +0x95 fp=0xc0000bfb78 sp=0xc0000bfae0 pc=0x9ef575
github.com/wailsapp/wails/v2/internal/frontend/desktop/windows/winc/w32.DispatchMessage(0x25075f94980)
        /Users/lykin/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/frontend/desktop/windows/winc/w32/user32.go:355 +0x8f fp=0xc0000bfc20 sp=0xc0000bfb78 pc=0xe9c5af
github.com/wailsapp/wails/v2/internal/frontend/desktop/windows/winc.RunMainLoop()
        /Users/lykin/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/frontend/desktop/windows/winc/app.go:84 +0xfc fp=0xc0000bfcd8 sp=0xc0000bfc20 pc=0xea591c
github.com/wailsapp/wails/v2/internal/frontend/desktop/windows.(*Frontend).RunMainLoop(0xc0001fee80)
        /Users/lykin/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/frontend/desktop/windows/frontend.go:205 +0x14 fp=0xc0000bfce8 sp=0xc0000bfcd8 pc=0xf65954
github.com/wailsapp/wails/v2/internal/app.(*App).Run(0xc000127bd0)
        /Users/lykin/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/app/app_production.go:19 +0x72 fp=0xc0000bfd50 sp=0xc0000bfce8 pc=0xf7d732
github.com/wailsapp/wails/v2/pkg/application.(*Application).Run(0xc00028c360)
        /Users/lykin/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/pkg/application/application.go:72 +0x18f fp=0xc0000bfde0 sp=0xc0000bfd50 pc=0xf7f4af
github.com/wailsapp/wails/v2.Run(0xc00009c640)
        /Users/lykin/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/wails.go:14 +0x2f fp=0xc0000bfe20 sp=0xc0000bfde0 pc=0xf7f90f
main.main()
        /Users/lykin/Documents/personal/tiny-rdm/main.go:44 +0x9dc fp=0xc0000bff68 sp=0xc0000bfe20 pc=0x129a2fc
runtime.main()
        /usr/local/opt/go/libexec/src/runtime/proc.go:267 +0x247 fp=0xc0000bffe0 sp=0xc0000bff68 pc=0x9a5767
runtime.goexit()
        /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000bffe8 sp=0xc0000bffe0 pc=0x9d3d81

goroutine 2 [force gc (idle)]:
runtime.gopark(0x1556470, 0x1aa38b0, 0x11, 0x14, 0x1)
        /usr/local/opt/go/libexec/src/runtime/proc.go:398 +0xfc fp=0xc000043f80 sp=0xc000043f50 pc=0x9a5bbc
runtime.goparkunlock(0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/opt/go/libexec/src/runtime/proc.go:404 +0x25 fp=0xc000043fb0 sp=0xc000043f80 pc=0x9a5c45
runtime.forcegchelper()
        /usr/local/opt/go/libexec/src/runtime/proc.go:322 +0xb5 fp=0xc000043fe0 sp=0xc000043fb0 pc=0x9a59d5
runtime.goexit()
        /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000043fe8 sp=0xc000043fe0 pc=0x9d3d81
created by runtime.init.6 in goroutine 1
        /usr/local/opt/go/libexec/src/runtime/proc.go:310 +0x1a

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1556470, 0x1aa40c0, 0xc, 0x14, 0x1)
        /usr/local/opt/go/libexec/src/runtime/proc.go:398 +0xfc fp=0xc000045f50 sp=0xc000045f20 pc=0x9a5bbc
runtime.goparkunlock(0x1?, 0x0?, 0x0?, 0x0?)
        /usr/local/opt/go/libexec/src/runtime/proc.go:404 +0x25 fp=0xc000045f80 sp=0xc000045f50 pc=0x9a5c45
runtime.bgsweep(0x0?)
        /usr/local/opt/go/libexec/src/runtime/mgcsweep.go:321 +0xe5 fp=0xc000045fc8 sp=0xc000045f80 pc=0x98db85
runtime.gcenable.func1()
        /usr/local/opt/go/libexec/src/runtime/mgc.go:200 +0x25 fp=0xc000045fe0 sp=0xc000045fc8 pc=0x981e25
runtime.goexit()
        /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000045fe8 sp=0xc000045fe0 pc=0x9d3d81
created by runtime.gcenable in goroutine 1
        /usr/local/opt/go/libexec/src/runtime/mgc.go:200 +0x66

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x1556470, 0x1aa4a00, 0xd, 0x14, 0x2)
        /usr/local/opt/go/libexec/src/runtime/proc.go:398 +0xfc fp=0xc000057f40 sp=0xc000057f10 pc=0x9a5bbc
runtime.goparkunlock(0x15911d0?, 0x0?, 0x0?, 0x0?)
        /usr/local/opt/go/libexec/src/runtime/proc.go:404 +0x25 fp=0xc000057f70 sp=0xc000057f40 pc=0x9a5c45
runtime.(*scavengerState).park(0x1aa4a00)
        /usr/local/opt/go/libexec/src/runtime/mgcscavenge.go:425 +0x45 fp=0xc000057f98 sp=0xc000057f70 pc=0x98ae25
runtime.bgscavenge(0x0?)
        /usr/local/opt/go/libexec/src/runtime/mgcscavenge.go:658 +0x65 fp=0xc000057fc8 sp=0xc000057f98 pc=0x98b3a5
runtime.gcenable.func2()
        /usr/local/opt/go/libexec/src/runtime/mgc.go:201 +0x25 fp=0xc000057fe0 sp=0xc000057fc8 pc=0x981dc5
runtime.goexit()
        /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000057fe8 sp=0xc000057fe0 pc=0x9d3d81
created by runtime.gcenable in goroutine 1
        /usr/local/opt/go/libexec/src/runtime/mgc.go:201 +0xa5

goroutine 18 [finalizer wait]:
runtime.gopark(0x1556198, 0x1afae90, 0x10, 0x14, 0x1)
        /usr/local/opt/go/libexec/src/runtime/proc.go:398 +0xfc fp=0xc000047e28 sp=0xc000047df8 pc=0x9a5bbc
runtime.runfinq()
        /usr/local/opt/go/libexec/src/runtime/mfinal.go:193 +0xfa fp=0xc000047fe0 sp=0xc000047e28 pc=0x980eda
runtime.goexit()
        /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000047fe8 sp=0xc000047fe0 pc=0x9d3d81
created by runtime.createfing in goroutine 1
        /usr/local/opt/go/libexec/src/runtime/mfinal.go:163 +0x45

goroutine 19 [syscall]:
runtime.notetsleepg(0x0?, 0x0?)
        /usr/local/opt/go/libexec/src/runtime/lock_sema.go:294 +0x31 fp=0xc000053f90 sp=0xc000053f48 pc=0x970fb1
os/signal.signal_recv()
        /usr/local/opt/go/libexec/src/runtime/sigqueue.go:152 +0x29 fp=0xc000053fb0 sp=0xc000053f90 pc=0x9cfb09
os/signal.loop()
        /usr/local/opt/go/libexec/src/os/signal/signal_unix.go:23 +0x17 fp=0xc000053fe0 sp=0xc000053fb0 pc=0xf7ea57
runtime.goexit()
        /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000053fe8 sp=0xc000053fe0 pc=0x9d3d81
created by os/signal.Notify.func1.1 in goroutine 1
        /usr/local/opt/go/libexec/src/os/signal/signal.go:151 +0x26

goroutine 20 [chan receive]:
runtime.gopark(0x1556130, 0xc0000c4058, 0xe, 0x17, 0x2)
        /usr/local/opt/go/libexec/src/runtime/proc.go:398 +0xfc fp=0xc000055ee8 sp=0xc000055eb8 pc=0x9a5bbc
runtime.chanrecv(0xc0000c4000, 0x0, 0x1)
        /usr/local/opt/go/libexec/src/runtime/chan.go:583 +0x2be fp=0xc000055f60 sp=0xc000055ee8 pc=0x96affe
runtime.chanrecv1(0x0?, 0x0?)
        /usr/local/opt/go/libexec/src/runtime/chan.go:442 +0x12 fp=0xc000055f88 sp=0xc000055f60 pc=0x96ad12
github.com/wailsapp/wails/v2/internal/signal.Start.func1()
        /Users/lykin/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/signal/signal.go:31 +0x25 fp=0xc000055fe0 sp=0xc000055f88 pc=0xf7efe5
runtime.goexit()
        /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000055fe8 sp=0xc000055fe0 pc=0x9d3d81
created by github.com/wailsapp/wails/v2/internal/signal.Start in goroutine 1
        /Users/lykin/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/signal/signal.go:29 +0xdb

goroutine 22 [GC worker (idle)]:
runtime.gopark(0x15561c0, 0xc000308000, 0x1a, 0x14, 0x0)
        /usr/local/opt/go/libexec/src/runtime/proc.go:398 +0xfc fp=0xc0002fff48 sp=0xc0002fff18 pc=0x9a5bbc
runtime.gcBgMarkWorker()
        /usr/local/opt/go/libexec/src/runtime/mgc.go:1293 +0xf4 fp=0xc0002fffe0 sp=0xc0002fff48 pc=0x983794
runtime.goexit()
        /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0002fffe8 sp=0xc0002fffe0 pc=0x9d3d81
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/local/opt/go/libexec/src/runtime/mgc.go:1217 +0x1c

goroutine 23 [GC worker (idle)]:
runtime.gopark(0x15561c0, 0xc00028bb80, 0x1a, 0x14, 0x0)
        /usr/local/opt/go/libexec/src/runtime/proc.go:398 +0xfc fp=0xc0002f9f48 sp=0xc0002f9f18 pc=0x9a5bbc
runtime.gcBgMarkWorker()
        /usr/local/opt/go/libexec/src/runtime/mgc.go:1293 +0xf4 fp=0xc0002f9fe0 sp=0xc0002f9f48 pc=0x983794
runtime.goexit()
        /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0002f9fe8 sp=0xc0002f9fe0 pc=0x9d3d81
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/local/opt/go/libexec/src/runtime/mgc.go:1217 +0x1c

goroutine 24 [GC worker (idle)]:
runtime.gopark(0x15561c0, 0xc00028bba0, 0x1a, 0x14, 0x0)
        /usr/local/opt/go/libexec/src/runtime/proc.go:398 +0xfc fp=0xc0002fbf48 sp=0xc0002fbf18 pc=0x9a5bbc
runtime.gcBgMarkWorker()
        /usr/local/opt/go/libexec/src/runtime/mgc.go:1293 +0xf4 fp=0xc0002fbfe0 sp=0xc0002fbf48 pc=0x983794
runtime.goexit()
        /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0002fbfe8 sp=0xc0002fbfe0 pc=0x9d3d81
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/local/opt/go/libexec/src/runtime/mgc.go:1217 +0x1c

goroutine 25 [GC worker (idle)]:
runtime.gopark(0x15561c0, 0xc00028bbc0, 0x1a, 0x14, 0x0)
        /usr/local/opt/go/libexec/src/runtime/proc.go:398 +0xfc fp=0xc0003f7f48 sp=0xc0003f7f18 pc=0x9a5bbc
runtime.gcBgMarkWorker()
        /usr/local/opt/go/libexec/src/runtime/mgc.go:1293 +0xf4 fp=0xc0003f7fe0 sp=0xc0003f7f48 pc=0x983794
runtime.goexit()
        /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0003f7fe8 sp=0xc0003f7fe0 pc=0x9d3d81
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/local/opt/go/libexec/src/runtime/mgc.go:1217 +0x1c

goroutine 26 [GC worker (idle)]:
runtime.gopark(0x15561c0, 0xc00028bbe0, 0x1a, 0x14, 0x0)
        /usr/local/opt/go/libexec/src/runtime/proc.go:398 +0xfc fp=0xc0003f9f48 sp=0xc0003f9f18 pc=0x9a5bbc
runtime.gcBgMarkWorker()
        /usr/local/opt/go/libexec/src/runtime/mgc.go:1293 +0xf4 fp=0xc0003f9fe0 sp=0xc0003f9f48 pc=0x983794
runtime.goexit()
        /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0003f9fe8 sp=0xc0003f9fe0 pc=0x9d3d81
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/local/opt/go/libexec/src/runtime/mgc.go:1217 +0x1c

goroutine 27 [GC worker (idle)]:
runtime.gopark(0x15561c0, 0xc00028bc00, 0x1a, 0x14, 0x0)
        /usr/local/opt/go/libexec/src/runtime/proc.go:398 +0xfc fp=0xc0003f3f48 sp=0xc0003f3f18 pc=0x9a5bbc
runtime.gcBgMarkWorker()
        /usr/local/opt/go/libexec/src/runtime/mgc.go:1293 +0xf4 fp=0xc0003f3fe0 sp=0xc0003f3f48 pc=0x983794
runtime.goexit()
        /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0003f3fe8 sp=0xc0003f3fe0 pc=0x9d3d81
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/local/opt/go/libexec/src/runtime/mgc.go:1217 +0x1c
rax     0x40c22b00e0280000
rbx     0xf0281fe900
rcx     0x6e1d2a2a0afa0000
rdi     0x28e0002bc6c0
rsi     0x28e0002e4000
rbp     0x0
rsp     0xf0281fe800
r8      0x0
r9      0x7ff9e2caafc0
r10     0x0
r11     0x0
r12     0xf0281fea10
r13     0x28e0002bc0c0
r14     0x28e0002e4510
r15     0xf0281fe820
rip     0x7ff9e2a67aae
rflags  0x10206
cs      0x33
fs      0x53
gs      0x2b
[1010/110955.622:ERROR:window_impl.cc(119)] Failed to unregister class Chrome_WidgetWin_0. Error = 0

**Comment by yogaxu** [comment]
> > @yogaxu @jizhong-xu 试下这个debug版本看看打开有没有控制台显示一些有用的信息 [Tiny RDM-debug.zip](https://github.com/tiny-craft/tiny-rdm/files/12844356/Tiny.RDM-debug.zip)
> 
> Exception 0xc0000005 0x0 0xffffffffffffffff 0x7ff9e2a67aae PC=0x7ff9e2a67aae
> 
> runtime.cgocall(0x9d5540, 0x1aa56c8) /usr/local/opt/go/libexec/src/runtime/cgocall.go:157 +0x3e fp=0xc0000bf9c8 sp=0xc0000bf990 pc=0x9699fe syscall.SyscallN(0x7ffa659ee040, {0xc0002f43a8?, 0x1, 0x100?}) /usr/local/opt/go/libexec/src/runtime/syscall_windows.go:544 +0x11d fp=0xc0000bfa50 sp=0xc0000bf9c8 pc=0x9d0b3d syscall.(*Proc).Call(0xc00028d9c0, {0xc0002f43a8, 0x1, 0x1}) /usr/local/opt/go/libexec/src/syscall/dll_windows.go:166 +0x7e fp=0xc0000bfae0 sp=0xc0000bfa50 pc=0x9eeb5e syscall.(*LazyProc).Call(0xc0000d00c0, {0xc0002f43a8, 0x1, 0x1}) /usr/local/opt/go/libexec/src/syscall/dll_windows.go:286 +0x95 fp=0xc0000bfb78 sp=0xc0000bfae0 pc=0x9ef575 github.com/wailsapp/wails/v2/internal/frontend/desktop/windows/winc/w32.DispatchMessage(0x25075f94980) /Users/lykin/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/frontend/desktop/windows/winc/w32/user32.go:355 +0x8f fp=0xc0000bfc20 sp=0xc0000bfb78 pc=0xe9c5af github.com/wailsapp/wails/v2/internal/frontend/desktop/windows/winc.RunMainLoop() /Users/lykin/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/frontend/desktop/windows/winc/app.go:84 +0xfc fp=0xc0000bfcd8 sp=0xc0000bfc20 pc=0xea591c github.com/wailsapp/wails/v2/internal/frontend/desktop/windows.(*Frontend).RunMainLoop(0xc0001fee80) /Users/lykin/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/frontend/desktop/windows/frontend.go:205 +0x14 fp=0xc0000bfce8 sp=0xc0000bfcd8 pc=0xf65954 github.com/wailsapp/wails/v2/internal/app.(*App).Run(0xc000127bd0) /Users/lykin/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/app/app_production.go:19 +0x72 fp=0xc0000bfd50 sp=0xc0000bfce8 pc=0xf7d732 github.com/wailsapp/wails/v2/pkg/application.(*Application).Run(0xc00028c360) /Users/lykin/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/pkg/application/application.go:72 +0x18f fp=0xc0000bfde0 sp=0xc0000bfd50 pc=0xf7f4af github.com/wailsapp/wails/v2.Run(0xc00009c640) /Users/lykin/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/wails.go:14 +0x2f fp=0xc0000bfe20 sp=0xc0000bfde0 pc=0xf7f90f main.main() /Users/lykin/Documents/personal/tiny-rdm/main.go:44 +0x9dc fp=0xc0000bff68 sp=0xc0000bfe20 pc=0x129a2fc runtime.main() /usr/local/opt/go/libexec/src/runtime/proc.go:267 +0x247 fp=0xc0000bffe0 sp=0xc0000bff68 pc=0x9a5767 runtime.goexit() /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000bffe8 sp=0xc0000bffe0 pc=0x9d3d81
> 
> goroutine 2 [force gc (idle)]: runtime.gopark(0x1556470, 0x1aa38b0, 0x11, 0x14, 0x1) /usr/local/opt/go/libexec/src/runtime/proc.go:398 +0xfc fp=0xc000043f80 sp=0xc000043f50 pc=0x9a5bbc runtime.goparkunlock(0x0?, 0x0?, 0x0?, 0x0?) /usr/local/opt/go/libexec/src/runtime/proc.go:404 +0x25 fp=0xc000043fb0 sp=0xc000043f80 pc=0x9a5c45 runtime.forcegchelper() /usr/local/opt/go/libexec/src/runtime/proc.go:322 +0xb5 fp=0xc000043fe0 sp=0xc000043fb0 pc=0x9a59d5 runtime.goexit() /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000043fe8 sp=0xc000043fe0 pc=0x9d3d81 created by runtime.init.6 in goroutine 1 /usr/local/opt/go/libexec/src/runtime/proc.go:310 +0x1a
> 
> goroutine 3 [GC sweep wait]: runtime.gopark(0x1556470, 0x1aa40c0, 0xc, 0x14, 0x1) /usr/local/opt/go/libexec/src/runtime/proc.go:398 +0xfc fp=0xc000045f50 sp=0xc000045f20 pc=0x9a5bbc runtime.goparkunlock(0x1?, 0x0?, 0x0?, 0x0?) /usr/local/opt/go/libexec/src/runtime/proc.go:404 +0x25 fp=0xc000045f80 sp=0xc000045f50 pc=0x9a5c45 runtime.bgsweep(0x0?) /usr/local/opt/go/libexec/src/runtime/mgcsweep.go:321 +0xe5 fp=0xc000045fc8 sp=0xc000045f80 pc=0x98db85 runtime.gcenable.func1() /usr/local/opt/go/libexec/src/runtime/mgc.go:200 +0x25 fp=0xc000045fe0 sp=0xc000045fc8 pc=0x981e25 runtime.goexit() /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000045fe8 sp=0xc000045fe0 pc=0x9d3d81 created by runtime.gcenable in goroutine 1 /usr/local/opt/go/libexec/src/runtime/mgc.go:200 +0x66
> 
> goroutine 4 [GC scavenge wait]: runtime.gopark(0x1556470, 0x1aa4a00, 0xd, 0x14, 0x2) /usr/local/opt/go/libexec/src/runtime/proc.go:398 +0xfc fp=0xc000057f40 sp=0xc000057f10 pc=0x9a5bbc runtime.goparkunlock(0x15911d0?, 0x0?, 0x0?, 0x0?) /usr/local/opt/go/libexec/src/runtime/proc.go:404 +0x25 fp=0xc000057f70 sp=0xc000057f40 pc=0x9a5c45 runtime.(*scavengerState).park(0x1aa4a00) /usr/local/opt/go/libexec/src/runtime/mgcscavenge.go:425 +0x45 fp=0xc000057f98 sp=0xc000057f70 pc=0x98ae25 runtime.bgscavenge(0x0?) /usr/local/opt/go/libexec/src/runtime/mgcscavenge.go:658 +0x65 fp=0xc000057fc8 sp=0xc000057f98 pc=0x98b3a5 runtime.gcenable.func2() /usr/local/opt/go/libexec/src/runtime/mgc.go:201 +0x25 fp=0xc000057fe0 sp=0xc000057fc8 pc=0x981dc5 runtime.goexit() /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000057fe8 sp=0xc000057fe0 pc=0x9d3d81 created by runtime.gcenable in goroutine 1 /usr/local/opt/go/libexec/src/runtime/mgc.go:201 +0xa5
> 
> goroutine 18 [finalizer wait]: runtime.gopark(0x1556198, 0x1afae90, 0x10, 0x14, 0x1) /usr/local/opt/go/libexec/src/runtime/proc.go:398 +0xfc fp=0xc000047e28 sp=0xc000047df8 pc=0x9a5bbc runtime.runfinq() /usr/local/opt/go/libexec/src/runtime/mfinal.go:193 +0xfa fp=0xc000047fe0 sp=0xc000047e28 pc=0x980eda runtime.goexit() /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000047fe8 sp=0xc000047fe0 pc=0x9d3d81 created by runtime.createfing in goroutine 1 /usr/local/opt/go/libexec/src/runtime/mfinal.go:163 +0x45
> 
> goroutine 19 [syscall]: runtime.notetsleepg(0x0?, 0x0?) /usr/local/opt/go/libexec/src/runtime/lock_sema.go:294 +0x31 fp=0xc000053f90 sp=0xc000053f48 pc=0x970fb1 os/signal.signal_recv() /usr/local/opt/go/libexec/src/runtime/sigqueue.go:152 +0x29 fp=0xc000053fb0 sp=0xc000053f90 pc=0x9cfb09 os/signal.loop() /usr/local/opt/go/libexec/src/os/signal/signal_unix.go:23 +0x17 fp=0xc000053fe0 sp=0xc000053fb0 pc=0xf7ea57 runtime.goexit() /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000053fe8 sp=0xc000053fe0 pc=0x9d3d81 created by os/signal.Notify.func1.1 in goroutine 1 /usr/local/opt/go/libexec/src/os/signal/signal.go:151 +0x26
> 
> goroutine 20 [chan receive]: runtime.gopark(0x1556130, 0xc0000c4058, 0xe, 0x17, 0x2) /usr/local/opt/go/libexec/src/runtime/proc.go:398 +0xfc fp=0xc000055ee8 sp=0xc000055eb8 pc=0x9a5bbc runtime.chanrecv(0xc0000c4000, 0x0, 0x1) /usr/local/opt/go/libexec/src/runtime/chan.go:583 +0x2be fp=0xc000055f60 sp=0xc000055ee8 pc=0x96affe runtime.chanrecv1(0x0?, 0x0?) /usr/local/opt/go/libexec/src/runtime/chan.go:442 +0x12 fp=0xc000055f88 sp=0xc000055f60 pc=0x96ad12 github.com/wailsapp/wails/v2/internal/signal.Start.func1() /Users/lykin/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/signal/signal.go:31 +0x25 fp=0xc000055fe0 sp=0xc000055f88 pc=0xf7efe5 runtime.goexit() /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000055fe8 sp=0xc000055fe0 pc=0x9d3d81 created by github.com/wailsapp/wails/v2/internal/signal.Start in goroutine 1 /Users/lykin/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/signal/signal.go:29 +0xdb
> 
> goroutine 22 [GC worker (idle)]: runtime.gopark(0x15561c0, 0xc000308000, 0x1a, 0x14, 0x0) /usr/local/opt/go/libexec/src/runtime/proc.go:398 +0xfc fp=0xc0002fff48 sp=0xc0002fff18 pc=0x9a5bbc runtime.gcBgMarkWorker() /usr/local/opt/go/libexec/src/runtime/mgc.go:1293 +0xf4 fp=0xc0002fffe0 sp=0xc0002fff48 pc=0x983794 runtime.goexit() /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0002fffe8 sp=0xc0002fffe0 pc=0x9d3d81 created by runtime.gcBgMarkStartWorkers in goroutine 1 /usr/local/opt/go/libexec/src/runtime/mgc.go:1217 +0x1c
> 
> goroutine 23 [GC worker (idle)]: runtime.gopark(0x15561c0, 0xc00028bb80, 0x1a, 0x14, 0x0) /usr/local/opt/go/libexec/src/runtime/proc.go:398 +0xfc fp=0xc0002f9f48 sp=0xc0002f9f18 pc=0x9a5bbc runtime.gcBgMarkWorker() /usr/local/opt/go/libexec/src/runtime/mgc.go:1293 +0xf4 fp=0xc0002f9fe0 sp=0xc0002f9f48 pc=0x983794 runtime.goexit() /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0002f9fe8 sp=0xc0002f9fe0 pc=0x9d3d81 created by runtime.gcBgMarkStartWorkers in goroutine 1 /usr/local/opt/go/libexec/src/runtime/mgc.go:1217 +0x1c
> 
> goroutine 24 [GC worker (idle)]: runtime.gopark(0x15561c0, 0xc00028bba0, 0x1a, 0x14, 0x0) /usr/local/opt/go/libexec/src/runtime/proc.go:398 +0xfc fp=0xc0002fbf48 sp=0xc0002fbf18 pc=0x9a5bbc runtime.gcBgMarkWorker() /usr/local/opt/go/libexec/src/runtime/mgc.go:1293 +0xf4 fp=0xc0002fbfe0 sp=0xc0002fbf48 pc=0x983794 runtime.goexit() /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0002fbfe8 sp=0xc0002fbfe0 pc=0x9d3d81 created by runtime.gcBgMarkStartWorkers in goroutine 1 /usr/local/opt/go/libexec/src/runtime/mgc.go:1217 +0x1c
> 
> goroutine 25 [GC worker (idle)]: runtime.gopark(0x15561c0, 0xc00028bbc0, 0x1a, 0x14, 0x0) /usr/local/opt/go/libexec/src/runtime/proc.go:398 +0xfc fp=0xc0003f7f48 sp=0xc0003f7f18 pc=0x9a5bbc runtime.gcBgMarkWorker() /usr/local/opt/go/libexec/src/runtime/mgc.go:1293 +0xf4 fp=0xc0003f7fe0 sp=0xc0003f7f48 pc=0x983794 runtime.goexit() /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0003f7fe8 sp=0xc0003f7fe0 pc=0x9d3d81 created by runtime.gcBgMarkStartWorkers in goroutine 1 /usr/local/opt/go/libexec/src/runtime/mgc.go:1217 +0x1c
> 
> goroutine 26 [GC worker (idle)]: runtime.gopark(0x15561c0, 0xc00028bbe0, 0x1a, 0x14, 0x0) /usr/local/opt/go/libexec/src/runtime/proc.go:398 +0xfc fp=0xc0003f9f48 sp=0xc0003f9f18 pc=0x9a5bbc runtime.gcBgMarkWorker() /usr/local/opt/go/libexec/src/runtime/mgc.go:1293 +0xf4 fp=0xc0003f9fe0 sp=0xc0003f9f48 pc=0x983794 runtime.goexit() /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0003f9fe8 sp=0xc0003f9fe0 pc=0x9d3d81 created by runtime.gcBgMarkStartWorkers in goroutine 1 /usr/local/opt/go/libexec/src/runtime/mgc.go:1217 +0x1c
> 
> goroutine 27 [GC worker (idle)]: runtime.gopark(0x15561c0, 0xc00028bc00, 0x1a, 0x14, 0x0) /usr/local/opt/go/libexec/src/runtime/proc.go:398 +0xfc fp=0xc0003f3f48 sp=0xc0003f3f18 pc=0x9a5bbc runtime.gcBgMarkWorker() /usr/local/opt/go/libexec/src/runtime/mgc.go:1293 +0xf4 fp=0xc0003f3fe0 sp=0xc0003f3f48 pc=0x983794 runtime.goexit() /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0003f3fe8 sp=0xc0003f3fe0 pc=0x9d3d81 created by runtime.gcBgMarkStartWorkers in goroutine 1 /usr/local/opt/go/libexec/src/runtime/mgc.go:1217 +0x1c rax 0x40c22b00e0280000 rbx 0xf0281fe900 rcx 0x6e1d2a2a0afa0000 rdi 0x28e0002bc6c0 rsi 0x28e0002e4000 rbp 0x0 rsp 0xf0281fe800 r8 0x0 r9 0x7ff9e2caafc0 r10 0x0 r11 0x0 r12 0xf0281fea10 r13 0x28e0002bc0c0 r14 0x28e0002e4510 r15 0xf0281fe820 rip 0x7ff9e2a67aae rflags 0x10206 cs 0x33 fs 0x53 gs 0x2b [1010/110955.622:ERROR:window_impl.cc(119)] Failed to unregister class Chrome_WidgetWin_0. Error = 0

@tiny-craft 之前试过源码运行，同样出现这个报错

**Comment by gitlii** [comment]
是不是杀毒软件导致，可以加到白名单或者关闭杀毒再试试

**Comment by yogaxu** [comment]
> 是不是杀毒软件导致，可以加到白名单或者关闭杀毒再试试

试过了，没用
